### ISSUE TITLE
PInvokeStackImbalance

### ISSUE THREAD

**Issue by CasparWaara** [Hwigaro/CoolerMaster-SDK-Wrapper#1]
I get this error if I use your test program. Effects seem to work ok but setting either single key or all keys to RGB color do not work  (functions return false and no color change).
```
Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'Sharp-SDK!Sharp_SDK.SDK::SetControlDevice' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'
```
I can get pass the exception with changing CallingConvention.StdCall to CallingConvention.Cdecl but still, setting the single or all keys to color do not work.

**Comment by Hwigaro** [comment]
![image](https://user-images.githubusercontent.com/13702320/35479475-e66109e8-03ce-11e8-8e4e-23cdeb86fe81.png)

Disable this and reconect your device, that worked for me

**Comment by CasparWaara** [comment]
That removes the exception but it doesn't make the changing color work.

`SDK.SetLedColor((byte)this.row.Value, (byte)this.column.Value, (byte)this.single_red.Value, (byte)this.single_green.Value, (byte)this.single_blue.Value);`

this returns always false.

 I'm using masterkeys pro s

**Comment by CasparWaara** [comment]
I tested the cooler master official SDK and it doesn't seem to work either with my keyboard. So I'm pretty sure there is nothing wrong with your library...closing this now
